server:
  port: 8070
spring:
  application:
    name: "config-server"
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/pragyasj/ukg-config.git
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true

