server:
  port: 8091
spring:
  application:
    name: "courses"
  datasource:
    url: jdbc:h2:mem:coursesdb
    username: sa
    password: ''
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect

